### ISSUE TITLE
Getting a 4097 TLS packet with unexpected error

### ISSUE THREAD

**Issue by macduffie** [google/cups-connector#111]
I'm running Linux Mint 17.2 with CUPS 1.7.2. I have GCP running via Chrome, but have about 15 printers and 300+ users, so I need to use the connector for better performance. I installed the GPC Connector and when I run it I get the following error: 

Failed to connect to CUPS server /var/run/cups/cups.sock:631 because 4097 A TLS packet with unexpected length was received.
goroutine 1 [running]:
github.com/golang/glog.stacks(0xd55c00, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0xcfdbe0, 0xc800000003, 0xc8200ca0c0, 0xad030d, 0x15, 0x62, 0x0)
	/home/user/go/src/github.com/golang/glog/glog.go:720 +0x2b8
github.com/golang/glog.(*loggingT).printDepth(0xcfdbe0, 0x3, 0x1, 0xc820111e20, 0x1, 0x1)
	/home/user/go/src/github.com/golang/glog/glog.go:646 +0x1b8
github.com/golang/glog.(*loggingT).print(0xcfdbe0, 0xc800000003, 0xc820111e20, 0x1, 0x1)
	/home/user/go/src/github.com/golang/glog/glog.go:637 +0x50
github.com/golang/glog.Fatal(0xc820111e20, 0x1, 0x1)
	/home/user/go/src/github.com/golang/glog/glog.go:1128 +0x49
main.main()
	/home/user/go/src/github.com/google/cups-connector/gcp-cups-connector/gcp-cups-connector.go:98 +0x1008

Thanks.

**Comment by jacobmarble** [comment]
@macduffie I don't know why this is happening, but I think an easy workaround would be to disable TLS. Since you are communicating with the CUPS server via /var/run/cups/cups.sock:631, this shouldn't cause any concern.

To test if this fixes the problem, try running the connector like this:
```sh
$ CUPS_ENCRYPTION=Never gcp-cups-connector
```
Check the logs, the second line should say `connected to CUPS server /var/run/cups/cups.sock:631 encrypting NEVER`

If that works, you can make it permanent by editing `/etc/cups/client.conf` and change `Encryption Something` to `Encryption Never`.
https://www.cups.org/documentation.php/doc-1.7/ref-client-conf.html?VERSION=1.7

Please follow-up when you have tried this.

**Comment by macduffie** [comment]
Setting CUPS_ENCRYPTION=Never resolved the problem. I edited the
client.conf file.

I had previously done a default install of Cups on Linux Mint with the
default settings. As far as I could tell encryption was not enabled, but the
connector is now working and processing print jobs much faster. Thank you.

Ed Gray
*Director of Information Technology*

*The MacDuffie School*
66 School St
Granby, MA 01033
(413) 255-0000 x356
egray@macduffie.org
http://macduffie.org

**Comment by jacobmarble** [comment]
OK, I'm glad it worked. This has happened to other users, still don't know why.
