### ISSUE TITLE
Connector not not working even though monitor says everything is OK

### ISSUE THREAD

**Issue by smartprinter** [google/cups-connector#113]
The monitor says this:
./connector-monitor 
Google Cloud Print CUPS Connector version DEV-linux
cups-printers=2
cups-raw-printers=0
gcp-printers=0
local-printers=2
cups-conn-qty=0
cups-conn-max-qty=50
jobs-done=0
jobs-error=0
jobs-in-progress=0

But google cloud print says both printers are offline.

What am I doing wrong? Any logs I need to look at?

**Comment by jacobmarble** [comment]
> But google cloud print says both printers are offline.

Where does it say that? At google.com/cloudprint? You have configured for local only, which means just that. Chrome browsers and ChromeOS devices on the local subnet can print directly to the CUPS Connector without telling google.com anything.

If that's not what you wanted, then run `gcp-cups-connector-util -init` to create a config file so that the CUPS Connector can communicate with google.com. You'll want to enable cloud printing.

**Comment by smartprinter** [comment]
Interesting. I thought I did enable GCP. It works now. Thanks!
