### ISSUE TITLE
gcp-cups-connector does not work with OS X El Capitan 10.11

### ISSUE THREAD

**Issue by 8cH9azbsFifZ** [google/cups-connector#123]
# gcp-cups-connector
  # echo $?
  0

Nothing happens. I followed the steps given in https://github.com/google/cups-connector/wiki/Build-from-source . In addition I had to # brew install bazaar. What else am I missing?

**Comment by jacobmarble** [comment]
Yes, I fumbled a commit yesterday. It's fixed now.

I haven't updated the OSX instructions to include bazaar, and others. I thought I was the only one using OSX.

**Comment by jacobmarble** [comment]
@8cH9azbsFifZ Have you tried this again?

**Comment by roodavis** [comment]
Are there any more detailed or step by step instructions for installing and using the cloud-print-connector on an OS X El Capitan CUPS server? I'm not sure if I need to try to find and install the avahi-libs. Do I install the xcode command line tools and then pickup further instructions somewhere else?

**Comment by jacobmarble** [comment]
You'll need to build from source, yes. You won't need avahi because OS X has Bonjour.

It's been a while since I built on OS X. Try this and let me know how far you get:
https://github.com/google/cloud-print-connector/wiki/Build-from-source

I don't know how to properly setup a service like this on OS X in a production environment.
