### ISSUE TITLE
HP Printer turn on/off - paused

### ISSUE THREAD

**Issue by ThomasJSVos** [google/cups-connector#207]
I have a HP Printer connected on my Raspberry Pi (Raspbian Jessie) and it can print successfully with Google Cloud Print thanks to this CUPS Connector. But when I turn off the printer (and leave the Raspberry Pi still on), and turn on the printer again, it doesn't print and shows this:
![hpprinter](https://cloud.githubusercontent.com/assets/10575035/14380895/96498a4c-fd82-11e5-8274-6dd33c79168c.png)

Any help is appreciated.

**Comment by ThomasJSVos** [comment]
Even when I restart the printer and the Raspberry Pi and start the Cups Connector, it still shows "paused", but command output doesn't give any errors:

    pi@raspberrypi:~ $ ./cups-connector/gcp-cups-connector
    Google Cloud Print CUPS Connector version 2016.01.02-linux
    Ready to rock as proxy 'HP_Photosmart_D7300_series' and in local mode

**Comment by KJS18** [comment]
Have you tried using the printer management system on your Raspberry Pi to un-pause the printer queue? I have only described this generically because I am unfamiliar with the Raspberry Pi.

**Comment by jacobmarble** [comment]
The connector polls the printer state every _n_ minutes, as determined by the `cups_printer_poll_interval` config option. I suggest you reduce this value to something like `10s`, then tail the log to see that Cloud Print is updated with the change, whenever the printer is turned on/off.

**Comment by ThomasJSVos** [comment]
Thanks! I'll give that a try.

**Comment by ThomasJSVos** [comment]
@jacobmarble I got the printing part working now, thanks. However, the startup script doesn't work. (/etc/rc.local).

I think that it isn't connected to the internet yet when it tries to start the Cups Connector. Any suggestions? It already has the `sleep 60` part before the command.

**Comment by ThomasJSVos** [comment]
And every time I start the script, the printed is listed as a new printer.
![screenshot_20160410-194908](https://cloud.githubusercontent.com/assets/10575035/14411904/71e80d2a-ff55-11e5-9749-adb3c49d1f1e.png)

**Comment by jacobmarble** [comment]
Have you looked at the logs after a failed reboot?

**Comment by KJS18** [comment]
If there aren't any CUPS connector log files already in /tmp, I suggest that you temporarily change the key line in /etc/rc.local from (as given in the wiki example):
`su --login --command /home/pi/cups-connector/gcp-cups-connector pi &`
to:
`logsave /tmp/rc.local_gcp_cups_connector_line.log su --login --command /home/pi/cups-connector/gcp-cups-connector pi &`
and then after rebooting your Rasberry Pi, inspect "rc.local_gcp_cups_connector_line.log" in /tmp.
Unless you do this you will miss any error messages about what might be preventing the CUPS connector **from starting** because the ampersand at the end of the line means that the command tries to run as a background process.

**Comment by agoode** [comment]
If you've updated your Raspbian (https://www.raspberrypi.org/documentation/raspbian/updating.md) then don't use the rc.local method anymore. Instead, try installing with https://github.com/google/cups-connector/wiki/Installing-on-Raspberry-Pi-Raspbian-Jessie. It is much more robust against these transient problems.

It sounds like you've got the printing issue fixed, so I'll close this now. Please open another issue if you are having other problems.
