### ISSUE TITLE
GCP connector running, but printers are unavalable

### ISSUE THREAD

**Issue by bnajdrovsky** [google/cups-connector#210]
I configured the GCP connector a couple of months ago, and it was working great.  Then, somewhere along the line, my printers became unavailable to the cloud print service.  I hadn't changed any configuration and the printers work just fine through CUPS on my LAN, but Google Cloud Print web site says that all my printers have been "offline for more than a month".  There are no errors in the log file and everything seems normal.  Here is the tail of the log output when starting GCP:

```
I [11/Apr/2016:09:41:39 -0500] connected to CUPS server /var/run/cups/cups.sock:631 encrypting REQUIRED
I [11/Apr/2016:09:41:39 -0500] Local printing enabled (Avahi client is running).
I [11/Apr/2016:09:41:39 -0500] Synchronizing printers, stand by
I [11/Apr/2016:09:41:39 -0500] Printers are already in sync; there are 3
I [11/Apr/2016:09:41:39 -0500] [Printer CLX-3175] Registered locally
I [11/Apr/2016:09:41:39 -0500] [Printer HLL2300D_Double_Sided] Registered locally
I [11/Apr/2016:09:41:39 -0500] [Printer HLL2300D] Registered locally
I [11/Apr/2016:09:41:39 -0500] Ready to rock as proxy 'home' and in local mode
I [11/Apr/2016:09:42:39 -0500] Synchronizing printers, stand by
I [11/Apr/2016:09:42:39 -0500] Printers are already in sync; there are 3
```

Again, the config has not been changed in any way, and it used to work both locally and over the Internet without any issues, but now none of the print queues show up as available in Cloud Print.

**Comment by jay0lee** [comment]
Did you upgrade cups-connector since your initial setup? If you did, you should run:

gcp-connector-util update-config-file --config-filename /path/to/your/gcp-cups-connector.config.json

to update the file. Then sanity check the file to make sure options are set properly (e.g. cloud_printing_enable is true)

Jay

**Comment by wligtenberg** [comment]
I am experiencing the same issue.
I didn't update in the mean time.
It just stopped working.

**Comment by jacobmarble** [comment]
Have the printers been used in the past month?
Have they been used via cloud (not via local) in the last month?
Do the printers still work via local?

I ask because there is a weird behavior built in to the Cloud Print cloud service that marks printers as offline if they haven't been printed to for more than one month.

**Comment by bnajdrovsky** [comment]
The printers have been used in the past month, but possibly not through the Cloud Print service, only directly on the LAN.   If Cloud Print marks printers as offline, is there a way to force it to refresh?

**Comment by jacobmarble** [comment]
I haven't done it in a while. Try printing to the printer, despite it's offline status. If the Android or Chrome client doesn't let you do this, then use the web client (https://www.google.com/cloudprint/#printers click red "print" button).

**Comment by bnajdrovsky** [comment]
Geez, looks like that was it.   Despite the fact that the printer was showing offline, I sent a print job to it and it indeed printed. So I guess this is just a bug with the Cloud Print website. Thanks for your help, jacobmarble.

**Comment by jacobmarble** [comment]
No prob.

**Comment by wligtenberg** [comment]
I can confirm this as well.
Wow, strange thing, that it marks it as offline then... I was really braking my head over that one.

**Comment by scottwilson312** [comment]
Does anyone know how to mark the printer as online? I have everything running, I can even print to the printers... it shows jobs as "Printed" in the console.... yet the printer still shows offline

**Comment by StrangelyTyped** [comment]
+1 on this, I just ran into the same issue - showing as offline despite 'updated <5 minutes ago>' and having just printed something from Chrome. 

It's a significant issue because while desktop chrome will let you print to an offline printer, the android print spooler just won't let you.

Deleting the printer from cloud print and then having the connector recreate it fixed it for me, but obviously people sharing printers etc can't necessarily do that.

**Comment by scottwilson312** [comment]
I have found that the printer will go offline if it hasn't received a print job in one month. What's weird is that even though my printers are getting print jobs, the "Last print job at <date>" hasn't updated since December 6th on any of my printers. Are you also experiencing this?

**Comment by ScottESanDiego** [comment]
To help prevent the "Offline" issue due to lack of print jobs, does anyone have a way to automatically send some fake print job (or print & cancel immediately) that we could shove into a cron job?
