### ISSUE TITLE
Is it possible to remove the connector on the Raspberry Pi end? Like removing it from command line?

### ISSUE THREAD

**Issue by tboythomas** [google/cups-connector#225]
Thanks

**Comment by agoode** [comment]
Did you edit your /etc/rc.local file to install this? If so, try editing that file and removing the line that starts the connector.

Otherwise, you can try `systemctl disable gcp` if you followed the instructions at https://github.com/google/cups-connector/wiki/Run-Connector-Automatically-on-Boot.

Please reopen if you need more help.
