### ISSUE TITLE
Hard for clients to distinguish local vs. cloud printers

### ISSUE THREAD

**Issue by jay0lee** [google/cups-connector#49]
When running cups-connector with local_printing: true, clients like Chrome OS see a local and cloud version of their printer (assuming they're on same network as printer). However, it's difficult for the client to determine which of these is currently selected without going to the selection menu every time. Consider the following scenario:

1. hplj200 is a cups printer shared by cups-connector and can printer both local and cloud.
1. user is almost always on same LAN as cups-connector and so normally has hplj200 local printer selected automatically and never changes it.
1. user travels but needs to print to hplj200 remotely. Since local hplj200 is not available, another printer like Google Docs is selected as the default after CTRL+P.
1. user clicks Change... button and selects cloud version of hplj200 and is able to print via GCP.
1. user returns to LAN so that hplj200 is local again.
1. user is not aware that they are now printing via hplj200 cloud as it has become the default.

A few possible ways this could be solved (some outside scope of cups-connector):
 * Chrome clients can become intelligent enough to prefer local printer when available, otherwise use cloud printer. This would be a GCP client issue, not cups-connector. Not sure if GCP clients can establish that local and cloud versions of a printer are the same printer.
 * Chrome clients should label (icon or text) the type of printer that is already selected. Maybe a cloud icon for the cloud printers and a LAN icon for local printers. This is outside the scope of cups-connector.
 * cups-connector appends " (local)" to all local printers.

The last option is the most straightforward though it may not be the ideal solution.

I'll work on a patch that adds optional values to append to local and cloud printer names (default to off).

**Comment by jacobmarble** [comment]
You're right, lots of client changes in these ideas.

- Unfortunately, when a printer is available both locally and via cloud, the policy is to favor cloud. This is because the cloud backend has all finishings available, applies them consistently, etc.
- Icons are good, especially since there's local-system and local-GCP. I'll talk to PMs about it.
- Currently, local is optional, cloud is required. In the future, local and cloud will both be optional. I think the " (local)" suffix is a good idea when both local and cloud are enabled. In fact, I favor no config option, just append it.

**Comment by jacobmarble** [comment]
Fixed in #51
