### ISSUE TITLE
Cannot use from behind a firewall

### ISSUE THREAD

**Issue by wcruppel** [google/cups-connector#62]
I'm a corporate user and have no authority to open firewall ports. Please add proxy server support.

The error I'm getting is:

F0909 17:08:40.408103   14144 connector.go:73] Failed to start XMPP conversation: Failed to dial XMPP service: Failed to connect to XMPP server: dial tcp [2404:6800:4003:c02::7d]:443: i/o timeout

FYI, I was able to run connector-init fine, so proxy for HTTP requests already seems to work.

Thanks.

**Comment by jacobmarble** [comment]
1) There is a bug open for adding proxy server support. I'll get started on that later this week.

2) I'm finishing up local-only support, which means that no Internet connection is actually needed. This works when all users are on the same subnet because it uses mDNS to announce/discover. I'm guessing that this isn't appropriate for your corporate environment, but it's worth mentioning.

**Comment by wcruppel** [comment]
Thanks Jacob

**Comment by jacobmarble** [comment]
@wcruppel Let's continue this conversation over at #58
