### ISSUE TITLE
Error: listen unix /var/run/cups-connector/monitor.sock: bind: no such file or directory

### ISSUE THREAD

**Issue by mnbf9rca** [google/cups-connector#63]
I managed to install and compile the connector on ubuntu LTS 14.04. I ran connector-init to generate the .json config file, but i can't get the connector to run. When executing at the command line i get this:
robert@ub:~/work/bin$ sudo ./connector &
[1] 3101
robert@ub:~/work/bin$ E0910 16:58:36.051510    3102 connector.go:33] Google Cloud Print CUPS Connector version DEV-linux
Google Cloud Print CUPS Connector version DEV-linux
F0910 16:58:38.039805    3102 connector.go:115] listen unix /var/run/cups-connector/monitor.sock: bind: no such file or directory
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc92d00, 0x0, 0x0, 0x0)
        /home/robert/work/src/github.com/golang/glog/glog.go:769 +0xb8
github.com/golang/glog.(*loggingT).output(0xc6e840, 0xc800000003, 0xc8200be0c0, 0xa4e5b8, 0xc, 0x73, 0x0)
        /home/robert/work/src/github.com/golang/glog/glog.go:720 +0x2b8
github.com/golang/glog.(*loggingT).printDepth(0xc6e840, 0xc800000003, 0x1, 0xc82007fe00, 0x1, 0x1)
        /home/robert/work/src/github.com/golang/glog/glog.go:646 +0x1b8
github.com/golang/glog.(*loggingT).print(0xc6e840, 0xc800000003, 0xc82007fe00, 0x1, 0x1)
        /home/robert/work/src/github.com/golang/glog/glog.go:637 +0x50
github.com/golang/glog.Fatal(0xc82007fe00, 0x1, 0x1)
        /home/robert/work/src/github.com/golang/glog/glog.go:1128 +0x49
main.main()
        /home/robert/work/src/github.com/google/cups-connector/connector/connector.go:115 +0x1486

[1]+  Exit 255                sudo ./connector

**Comment by mnbf9rca** [comment]
p.s. I have logfiles (ERROR, FATAL, INFO, WARNING) too - not sure if they contain e.g. oauth token so haven't posted them but let me know if i should.

**Comment by jacobmarble** [comment]
When you ran connector-init, there was a warning about this. The easy fix is to edit your config file, and change monitor_socket_filename to something like "/tmp/cups-connector-monitor.sock"

**Comment by abalnflx** [comment]
Hey mnbf9rca,

I've run into the same thing. You most likely need to create the folder
/var/run/cups-connector

In the read me it states to do so:
Prepare monitor socket directory

Make sure that the socket directory (see monitor_socket_filename above),
exists and is writeable by the user that the connector will run as:

$ sudo mkdir /var/run/cups-connector
$ sudo chown $USER /var/run/cups-connector

Of course, you'll have to do this every time the platform boots, because
/var/run isn't persistent. If you prefer to keep things simple, then forget
what I said before about mkdir and chown, and change the config file value
for monitor_socket_filename to /tmp/cups-connector-monitor.sock.



On Thu, Sep 10, 2015 at 9:01 AM, mnbf9rca <notifications@github.com> wrote:

> p.s. I have logfiles (ERROR, FATAL, INFO, WARNING) too - not sure if they
> contain e.g. oauth token so haven't posted them but let me know if i should.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/cups-connector/issues/63#issuecomment-139292232>
> .
>



-- 
Andrew Balingit
Client Technology Specialist | Netflix, Inc. | C: 650.200.3739 | D:
310.975.8712

**Comment by mnbf9rca** [comment]
i thought i'd done that! but yes, you're right, i had missed this step. Thanks!
