### ISSUE TITLE
Use more descriptive names for the binaries

### ISSUE THREAD

**Issue by rrthomas** [google/cups-connector#80]
I suggest `s/connector/gcp-cups/`, as `connector` is too generic.

**Comment by jacobmarble** [comment]
The opposite of a "CUPS connector" is a "CUPS virtual driver" which connects CUPS clients to GCP printers. The most popular one I'm aware of is called "[CUPS Cloud Print](https://github.com/simoncadman/CUPS-Cloud-Print)", which I find too ambiguous. I needed something more descriptive than "CUPS plus Cloud Print".

So the full name is "Google Cloud Print CUPS Connector" and I'm a lazy typist so "cups-connector" is the repo name.

For the binaries, `gcp-cups` is too ambiguous because of the virtual driver. I think a fair compromise would be `gcp-cups-connector` because it's the minimum that covers all bases.

Your thoughts?

**Comment by rrthomas** [comment]
I agree that `gcp-cups-connector` is reasonable. Users who are lazy typists such as us should not be typing any of its commands often, and when we do, we can use Tab completion or our other favorite lazy mechanisms. Developers, who run the commands more often, may prefer more aggressive abbreviation, but shouldn't inflict their needs on users!

**Comment by jacobmarble** [comment]
Fixed in #92
