### ISSUE TITLE
Need appropriate systemd service file 

### ISSUE THREAD

**Issue by hubertbanas** [google/cups-connector#94]
Something like this should do it:

```bash
/etc/systemd/system/gcp.service

[Unit]
Description=Google Cloud Print CUPS Connector
After=printer.target

[Service]
ExecStart=/opt/gcp_cups_connector/gcp-cups-connector -config-filename /etc/gcp_cups_connector/cups-connector.config.json
Restart=on-abort
User=gcp
Group=gcp

[Install]
WantedBy=multi-user.target
```

There are few assumptions here:

1) system user/group "gcp" exists
2) gcp-cups-connector is located at /opt/gcp_cups_connector/gcp-cups-connector
3) gcp user has execute rights to /opt/gcp_cups_connector/gcp-cups-connector
4) cups-connector.config.json is located at /etc/gcp_cups_connector/cups-connector.config.json
5) gcp user has read rights to /etc/gcp_cups_connector/cups-connector.config.json

**Comment by jacobmarble** [comment]
@hubertbanas I'm hesitant to add this to the repository for now because I'm not sufficiently familiar with systemd to maintain (answer questions, improve, fix) this service file.

It would be more appropriate, and certainly appreciated, if you added a systemd page to the wiki, including the file example you wrote above.

**Comment by hubertbanas** [comment]
Done. Thanks!
